MHPGroupProject/Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Services;
using Web.Model;

namespace Web.Controllers
{
	public class AuthController : Controller
	{
		public IActionResult Index()
		{
			return null;
		}

		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Login(string returnUrl, AuthUser user)
		{
			MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());

			User baseuser = await mHPAPI.Authenticate(user.Username, user.Pass);
            if (baseuser != null)
            {
				CurrentUser.User = baseuser;
            }
			return LocalRedirect(returnUrl);
		}
		[HttpGet]
		public async Task<IActionResult> Register()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Register(string returnUrl, AuthUser user)
		{
			try
			{
				MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());
				User newUser = await mHPAPI.RegisterUser(user);
				User baseuser = await mHPAPI.Authenticate(user.Username, user.Pass);

				if (baseuser != null)
				{
					CurrentUser.User = baseuser;
				}
			}
			catch (Exception)
			{
			}
			
			return LocalRedirect(returnUrl);
		}

		[HttpGet]
		public async Task<IActionResult> Logout()
		{
			CurrentUser.User = null;
			return LocalRedirect("/");
		}
	}
}

MHPGroupProject/Web/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.DTO;
using Web.Model;
using Web.Services;
using Web.ViewModel;

namespace Web.Controllers
{
	public class ChatController : Controller
	{
		public IActionResult OpenChat()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> OpenChat(UserListViewModel userListViewModel)
        {

			MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());


			//Get users for userlist
			List<UserResponse> users = await mHPAPI.GetFriendList();

			userListViewModel.Users = users;

			List<ChatResponse> chats = await mHPAPI.FindChats();

			userListViewModel.ExistingChats = chats;

			ViewData["UserList"] = userListViewModel;


			//Find Chat from id
			ChatResponse chat = await mHPAPI.FindSpecificChat(userListViewModel.SelectedChat);

			ChatViewModel chatViewModel = new ChatViewModel
			{
				Chat = chat
			};


			return View(chatViewModel);
        }

		[HttpGet]
		public async Task<IActionResult> CreateChat()
		{
			if (CurrentUser.User == null || !CurrentUser.User.Roles.Any(x => x == "Admin"))
			{
				return LocalRedirect("/");
			}


			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CreateChat(UserListViewModel userListViewModel)
		{
			if (CurrentUser.User == null || !CurrentUser.User.Roles.Any(x => x == "Admin"))
			{
				return LocalRedirect("/");
			}

			List<string> userIds = new List<string>();

			userIds.Add(CurrentUser.User.Id);
			userIds.Add(userListViewModel.ChosenUser);

			CreateChatDTO createChat = new CreateChatDTO()
			{
				UserIds = userIds
			};
			MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());
			try
			{
				Chat chat = await mHPAPI.CreateChat(createChat);
			}
			catch (Exception)
			{

			}

			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public async Task<IActionResult> SendMessage(string returnUrl, ChatViewModel chatViewModel, string Message)
        {
			chatViewModel.SendMessage.Message = Message;
			MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());

			try
            {
				Message message = await mHPAPI.SendMessage(chatViewModel.SendMessage);

			}
            catch
            {

            }

			return LocalRedirect(returnUrl);
		}

	}
}

MHPGroupProject/Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.DTO;
using Web.Model;
using Web.Services;
using Web.ViewModel;

namespace Web.Controllers
{
	public class HomeController : Controller
	{
		public async Task<IActionResult> Index()
		{
			//Return created chats for userlist
			MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());

			List<UserResponse> users = await mHPAPI.GetFriendList();

			UserListViewModel userListViewModel = new UserListViewModel();
			userListViewModel.Users = users;

			List<ChatResponse> chats = await mHPAPI.FindChats();

			userListViewModel.ExistingChats = chats;

			ViewData["UserList"] = userListViewModel;

			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}
	}
}

MHPGroupProject/Web/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Model;
using Web.Services;
using Web.ViewModel;

namespace Web.Controllers
{
	public class PostController : Controller
	{
		public async Task<IActionResult> IndexAsync()
		{
			if (CurrentUser.User == null || !CurrentUser.User.Roles.Any(x => x == "Admin"))
			{
				return LocalRedirect("/");
			}

			List<PostViewModel> postViewModels = null;
			try
			{
				MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());
				List<Post> posts = await mHPAPI.GetPosts();
				postViewModels = posts
					.Select(x => new PostViewModel ( 
						x.Content, 
						x.Tags.Select(t => new TagViewModel(t.Name)).ToList(), 
						new UserViewModel(mHPAPI.GetUserById(x.UserID).Result),
						x.CreatedDate,
						x.Comments.Select(c => new CommentViewModel(c.Content, c.User.UserName, c.CreatedDateTime)).ToList()
					)).ToList();
			}
			catch (Exception)
			{

			}
			return View(postViewModels);
		}

		[HttpGet]
		public async Task<IActionResult> CreatePost()
		{
			if (CurrentUser.User == null || !CurrentUser.User.Roles.Any(x => x == "Admin"))
			{
				return LocalRedirect("/");
			}
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CreatePost(string returnUrl, PostValidationViewModel postValidationViewModel)
		{
			if (CurrentUser.User == null || !CurrentUser.User.Roles.Any(x => x == "Admin"))
			{
				return LocalRedirect("/");
			}
			MHPAPI mHPAPI = new MHPAPI("https://localhost:44353", new System.Net.Http.HttpClient());
			try
			{
				Post post = await mHPAPI.CreatePost(postValidationViewModel);
			}
			catch (Exception)
			{
				
			}
			
			return LocalRedirect(returnUrl);
		}
	}
}

MHPGroupProject/Web/Views/Chat/OpenChat.cshtml
@model Web.ViewModel.ChatViewModel
@using Web.Model
@using Web.DTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<div>
    <div>
        @if (Model.Chat.Messages != null)
        {
            @foreach (ChatMessageDTO message in Model.Chat.Messages)
            {
                <p>@message.CreatedDate.ToString() - insert username here</p>
                <p>@message.Content</p>
            }
         }
         else
         {
            <p>No messages currently</p>
         }

    </div>
    <form method="post" asp-controller="Chat" asp-action="SendMessage" asp-route-returnUrl="@Url.Action("OpenChat", "Chat")">
        <textarea type="text" asp-for="SendMessage.Message" name="Message"></textarea>
        <input asp-for="SendMessage.UserID" value="@CurrentUser.User.Id" type="hidden" />
        <input asp-for="SendMessage.ChatID" value="@Model.Chat.Id" type="hidden" />
        <input type="submit" />
    </form>
</div>

MHPGroupProject/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
}

<div class="">

    <img src="https://www.gsv.dk/content/uploads/products/001-1495-9999/Gravemaskine3032T_0-768x432.png" alt="Gravmaskine" />
</div>

MHPGroupProject/Web/Views/Post/CreatePost.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model ViewModel.PostValidationViewModel

<div class="col-12 align-self-center">
    <form method="post" asp-controller="Post" asp-action="CreatePost" asp-route-returnUrl="@Url.Action("Index", "Post")">
        <label for="username" class="col-12">
            Content
            <textarea asp-for="Content" type="text" id="content" name="content" class="textareaStyle"></textarea>
        </label>
        <label for="password" class="col-12">
            Tags (seperate by comma(,))
            <input asp-for="Tags" id="tags" type="text" name="tags" value="" />
        </label>
        <button type="submit">Post</button>
    </form>
</div>

MHPGroupProject/Web/Views/Post/Index.cshtml
@model List<ViewModel.PostViewModel>;
@foreach (var item in Model)
{
<div>
    <p>
        @item.Content
    </p>
    <span class="createdDate">
        @item.CreatedDate
    </span>
    <span class="Author">
        @item.UserViewModel.UserName
    </span>
    <div class="tag">
        @foreach (var tag in item.Tags)
        {
            <span>
                @tag.Name + ", ";
            </span>
        }
    </div>

    <div class="comments">
        @foreach (var comment in item.Comments)
        {
            <div class="comment">
                <p>
                    @comment.Content;
                </p>
                <span class="commentUser">
                    @comment.UserName
                </span>
                <span>
                    @comment.CreatedDate
                </span>
            </div>
        }
    </div>
</div>
}

MHPGroupProject/Web/Views/Shared/_Layout.cshtml
@using Web
@using Web.Model
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if ((CurrentUser.User != null) && (CurrentUser.User.Roles.Find(x => x == "Admin")) != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Post" asp-action="Index">All posts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Post" asp-action="CreatePost">Create post</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register user</a>
                                </li>
                            }
                        }
                    </ul>
                    </div>
            </div>
        </nav>
    </header>
    <div class="container" style="max-width:100%;">
        <main role="main" class="pb-3">
            <div class="text-center row">
                <div class="col-12">
                    <h1 class="display-4">Welcome</h1>
                    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
                </div>
                @{

                    if ((CurrentUser.User != null) && (CurrentUser.User.Roles.Find(x => x == "Admin")) != null)
                    {
                        <div class="col-9" style="min-height:800px; background-color:navy;">
                            @RenderBody()
                        </div>
                        <div class="col-3" style="background-color: #9b0d0d; min-height:800px;">
                            @await Html.PartialAsync("_UserListPartial", ViewData["UserList"]);
                        </div>
                    }
                    else
                    {

                        <div class="col-12 text-center">
                            @RenderBody()
                        </div>
                    }
                }
            </div>
        </main>
    </div>

    <div class="chatmesssage">

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MHPGroupProject/Web/Views/Shared/_UserListPartial.cshtml
@model Web.ViewModel.UserListViewModel
@using Web.DTO
@using System.Linq

@foreach (UserResponse user in Model.Users)
{
<li>
    <p>@user.Username</p>
    @{
        ChatResponse chat = Model.ExistingChats.Find(x => x.ChatUsers.Any(x => x.UserID == user.Id));

    } 
    @if (chat != null)
    {
        <form asp-controller="Chat" asp-action="OpenChat">
            <input type="hidden" asp-for="SelectedChat" name="SelectedChat" id="SelectedChat" value="@chat.Id" />
            <input type="submit" value="Chat" />
        </form>
    }
    else
    {
        <form asp-controller="Chat" asp-action="CreateChat">
            <input type="hidden" asp-for="ChosenUser" name="ChosenUser" id="ChosenUser" value="@user.Id" />
            <input type="submit" value="Chat" />
        </form>

    }

</li>
 }